admin_listen_address: "0.0.0.0:8080"
log_level: "info"
module_path: "examples/modules"
identity_file_path: "agent-identity.json"
policy_path: "configs/policy.yaml"
signing_priv_key_path: "configs/signing_private.key"
controller_path: "controllers"
admin_policy_path: "configs/admin_policy.rego"
p2p:
  listen_addresses:
    - "/ip4/0.0.0.0/tcp/0"
    - "/ip4/0.0.0.0/tcp/8080"
    - "/ip4/0.0.0.0/tcp/80"
    - "/ip4/0.0.0.0/tcp/443"
    - "/ip4/0.0.0.0/udp/8080/quic-v1"
    - "/ip4/0.0.0.0/udp/80/quic-v1"
    - "/ip4/0.0.0.0/udp/443/quic-v1"
    - "/ip4/0.0.0.0/tcp/8080/ws"
    - "/ip4/0.0.0.0/tcp/80/ws"
    - "/ip4/0.0.0.0/tcp/443/ws"
  bootstrap_peers: []
  heartbeat_interval: "10s"
update:
  server_url: "http://127.0.0.1:8000/release.json"
  check_interval: "1m"
  public_key: "234447437978db889caa7bc4115d873700d0821f0deedc0c0b03651d59fbc7f6"